version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: angie
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: spring-api
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: angiematiz1808@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 18082001
    ports:
      - "8181:80"